version: '3'
services:
  ldap:
    image: osixia/openldap
    command: --loglevel debug
    environment:
      - LDAP_ORGANISATION=European Data Incubator
      - LDAP_DOMAIN=edincubator.eu
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
    volumes:
      - /var/lib/ldap:/var/lib/ldap
      - /etc/ldap/slapd.d:/etc/ldap/slapd.d
    networks:
      - edincubator
    ports:
      - "389:389"
      - "636:636"
    phpldapadmin:
      image: osixia/phpldapadmin
      environment:
        - PHPLDAPADMIN_LDAP_HOSTS=ldap
  portus:
    image: opensuse/portus:head
    environment: 
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false

      - CCONFIG_PREFIX=PORTUS

      - PORTUS_DB_HOST=portus_db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # Since we have no nginx in insecure mode, portus have to
      # serve the static files
      - RAILS_SERVE_STATIC_FILES=true

      # LDAP
      - PORTUS_LDAP_ENABLED=true
      - PORTUS_LDAP_HOSTNAME=ldap
      - PORTUS_LDAP_PORT=389
      - PORTUS_LDAP_UID=cn
      - PORTUS_LDAP_BASE=dc=edincubator,dc=eu
      - PORTUS_LDAP_GROUP_BASE=ou=group,dc=edincubator,dc=eu
      - PORTUS_LDAP_FILTER=
      - PORTUS_LDAP_AUTHENTICATION_ENABLED=true
      - PORTUS_LDAP_AUTHENTICATION_BIND_DN=cn=admin,dc=edincubator,dc=eu
      - PORTUS_LDAP_AUTHENTICATION_PASSWORD=${LDAP_ADMIN_PASSWORD}
    depends_on:
      - portus_db
      - ldap
    networks:
      - edincubator
    volumes:
      - ./secrets:/certificates:ro
      - ./secrets/ldap:/ldap-certificates:ro

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - portus_db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=portus_db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # LDAP
      - PORTUS_LDAP_ENABLED=true
      - PORTUS_LDAP_HOSTNAME=ldap
      - PORTUS_LDAP_PORT=389
      - PORTUS_LDAP_UID=cn
      - PORTUS_LDAP_BASE=dc=edincubator,dc=eu
      - PORTUS_LDAP_GROUP_BASE=ou=group,dc=edincubator,dc=eu
      - PORTUS_LDAP_FILTER=
      - PORTUS_LDAP_AUTHENTICATION_ENABLED=true
      - PORTUS_LDAP_AUTHENTICATION_BIND_DN=cn=admin,dc=edincubator,dc=eu
      - PORTUS_LDAP_AUTHENTICATION_PASSWORD=${LDAP_ADMIN_PASSWORD}

      - PORTUS_BACKGROUND=true
    networks:
      - edincubator
    volumes:
      - ./secrets:/certificates:ro
      - ./secrets/ldap:/ldap-certificates:ro

  portus_db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql
    networks:
      - edincubator
  
  registry:
    image: library/registry:2.6
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: http://portus.edincubator.eu/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: registry.edincubator.eu
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://portus.edincubator.eu/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
    networks:
      - edincubator

  jupyterhub:
    image: edincubator/jupyterhub
    environment:
      DOCKER_NETWORK_NAME: ediservices_edincubator
    volumes:
      - /etc/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      edincubator:
        aliases:
          - jupyterhub

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - portus
      - registry
      - jupyterhub
    networks:
      edincubator:
        aliases:
          - portus.edincubator.eu
          - registry.edincubator.eu

networks:
  edincubator:
    ipam:
      driver: default
      config:
        - subnet: "172.13.0.0/16"